// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameApp = "app"

// App 应用
type App struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id,string"`                 // id
	AppName      string    `gorm:"column:appName;comment:应用名称" json:"appName"`                                          // 应用名称
	Cover        string    `gorm:"column:cover;comment:应用封面" json:"cover"`                                              // 应用封面
	InitPrompt   string    `gorm:"column:initPrompt;comment:应用初始化的 prompt" json:"initPrompt"`                           // 应用初始化的 prompt
	CodeGenType  string    `gorm:"column:codeGenType;comment:代码生成类型（枚举）" json:"codeGenType"`                            // 代码生成类型（枚举）
	DeployKey    string    `gorm:"column:deployKey;comment:部署标识" json:"deployKey"`                                      // 部署标识
	DeployedTime time.Time `gorm:"column:deployedTime;comment:部署时间" json:"deployedTime"`                                // 部署时间
	Priority     int32     `gorm:"column:priority;not null;comment:优先级" json:"priority"`                                // 优先级
	UserID       int64     `gorm:"column:userId;not null;comment:创建用户id" json:"userId"`                                 // 创建用户id
	EditTime     time.Time `gorm:"column:editTime;not null;default:CURRENT_TIMESTAMP;comment:编辑时间" json:"editTime"`     // 编辑时间
	CreateTime   time.Time `gorm:"column:createTime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createTime"` // 创建时间
	UpdateTime   time.Time `gorm:"column:updateTime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateTime"` // 更新时间
	IsDelete     int32     `gorm:"column:isDelete;not null;comment:是否删除" json:"isDelete"`                               // 是否删除
}

// TableName App's table name
func (*App) TableName() string {
	return TableNameApp
}
