// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameChatHistory = "chat_history"

// ChatHistory 对话历史
type ChatHistory struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id,string"`                 // id
	Message     string    `gorm:"column:message;not null;comment:消息内容" json:"message"`                                 // 消息内容
	MessageType string    `gorm:"column:messageType;not null;comment:消息类型：user/ai" json:"messageType"`                 // 消息类型：user/ai
	AppID       int64     `gorm:"column:appId;not null;comment:应用ID" json:"appId"`                                     // 应用ID
	UserID      int64     `gorm:"column:userId;not null;comment:用户ID" json:"userId"`                                   // 用户ID
	TurnNumber  int32     `gorm:"column:turnNumber;not null;default:1;comment:对话轮数" json:"turnNumber"`                 // 对话轮数
	CreateTime  time.Time `gorm:"column:createTime;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"createTime"` // 创建时间
	UpdateTime  time.Time `gorm:"column:updateTime;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updateTime"` // 更新时间
	IsDelete    int32     `gorm:"column:isDelete;not null;comment:是否删除" json:"isDelete"`                               // 是否删除
}

// TableName ChatHistory's table name
func (*ChatHistory) TableName() string {
	return TableNameChatHistory
}
