// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User 用户
type User struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:id" json:"id,string"`                   // id
	UserAccount  string    `gorm:"column:user_account;not null;comment:账号" json:"user_account"`                           // 账号
	UserPassword string    `gorm:"column:user_password;not null;comment:密码" json:"user_password"`                         // 密码
	UserName     string    `gorm:"column:user_name;comment:用户昵称" json:"user_name"`                                        // 用户昵称
	UserAvatar   string    `gorm:"column:user_avatar;comment:用户头像" json:"user_avatar"`                                    // 用户头像
	UserProfile  string    `gorm:"column:user_profile;comment:用户简介" json:"user_profile"`                                  // 用户简介
	UserRole     string    `gorm:"column:user_role;not null;default:user;comment:用户角色：user/admin" json:"user_role"`       // 用户角色：user/admin
	EditTime     time.Time `gorm:"column:edit_time;not null;default:CURRENT_TIMESTAMP;comment:编辑时间" json:"edit_time"`     // 编辑时间
	CreateTime   time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"create_time"` // 创建时间
	UpdateTime   time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP;comment:更新时间" json:"update_time"` // 更新时间
	IsDelete     int32     `gorm:"column:is_delete;not null;comment:是否删除" json:"is_delete"`                               // 是否删除
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
