// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fmt"
	"github.com/chosenlau/noCodeAI/config"
	"github.com/chosenlau/noCodeAI/internal/ai/agent"
	"github.com/chosenlau/noCodeAI/internal/ai/aitools"
	"github.com/chosenlau/noCodeAI/internal/ai/graph/node"
	"github.com/chosenlau/noCodeAI/internal/ai/graph/workflow"
	"github.com/chosenlau/noCodeAI/internal/ai/llm"
	"github.com/chosenlau/noCodeAI/internal/core"
	"github.com/chosenlau/noCodeAI/internal/core/saver"
	"github.com/chosenlau/noCodeAI/internal/core/store"
	"github.com/chosenlau/noCodeAI/internal/dal"
	"github.com/chosenlau/noCodeAI/internal/handler"
	"github.com/chosenlau/noCodeAI/internal/logic"
	"github.com/chosenlau/noCodeAI/internal/router"
	"github.com/chosenlau/noCodeAI/internal/service"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/google/wire"
	"time"
)

// Injectors from wire.go:

func InitializeApp() (*server.Hertz, error) {
	configConfig := config.InitConfig()
	db := dal.InitDB(configConfig)
	client := dal.InitRedis(configConfig)
	userService := logic.NewUserService(db, client)
	userHandler := handler.NewUserHandler(userService)
	chatModelWrapperAdaptor, err := ProvideChatModel(configConfig)
	if err != nil {
		return nil, err
	}
	memoryStore := store.NewRedisMemoryStore(client, 20, 24*time.Hour)
	chatHistoryService := logic.NewChatHistoryService(db, memoryStore)
	toolManager, err := aitools.NewToolManager()
	if err != nil {
		return nil, err
	}
	htmlCodeGenAgent := agent.NewHtmlCodeGenAgent(chatModelWrapperAdaptor, nil, nil, nil)
	multiFileCodeGenAgent := agent.NewMultiFileCodeGenAgent(chatModelWrapperAdaptor, nil, nil, nil)
	vueCodeGenAgent := agent.NewVueCodeGenAgent(chatModelWrapperAdaptor, nil, nil, toolManager, nil)
	codeGenAgentFactory := agent.NewCodeGenAgentFactory(
		htmlCodeGenAgent,
		multiFileCodeGenAgent,
		vueCodeGenAgent,
	)
	codeSaver, err := saver.NewCodeSaver()
	if err != nil {
		return nil, err
	}
	noCodeAIGenFacade := core.NewNoCodeAIGenFacade(codeGenAgentFactory, codeSaver)
	routingAgent := agent.NewCodeGenTypeRoutingAgent(chatModelWrapperAdaptor, nil, nil)
	qualityAgent := agent.NewCodeQualityCheckAgent(chatModelWrapperAdaptor, nil, nil)
	simpleWorkflow := workflow.NewSimpleWorkflow(
		node.NewRouterNode(routingAgent),
		node.NewPromptEnhancerNode(),
		node.NewCodeGeneratorNode(noCodeAIGenFacade),
		node.NewCodeQualityCheckNode(qualityAgent),
	)
	appService := logic.NewAppService(noCodeAIGenFacade, userService, chatHistoryService, db, memoryStore, simpleWorkflow)
	appHandler := handler.NewAppHandler(appService, userService, chatHistoryService)
	chatHistoryHandler := handler.NewChatHistoryHandler(chatHistoryService, userService)
	hertz := initServer(configConfig, userHandler, appHandler, chatHistoryHandler, userService)
	return hertz, nil
}

// wire.go:

func ProvideChatModel(cfg *config.Config) (agent.ChatModelWrapperAdaptor, error) {
	switch cfg.AI.Provider {
	case "claude":
		return llm.NewClaudeChatModel(cfg), nil
	case "openai":
		return llm.NewOpenAIChatModel(cfg), nil
	default:
		return nil, fmt.Errorf("unsupported llm provider: %s", cfg.AI.Provider)
	}
}

var configSet = wire.NewSet(config.InitConfig)

var dbSet = wire.NewSet(dal.InitDB, dal.InitRedis)

var serviceSet = wire.NewSet(logic.NewAppService, wire.Bind(new(service.IAppService), new(*logic.AppService)), logic.NewUserService, wire.Bind(new(service.IUserService), new(*logic.UserService)), logic.NewChatHistoryService, wire.Bind(new(service.IChatHistoryService), new(*logic.ChatHistoryService)))

var handlerSet = wire.NewSet(handler.NewUserHandler, handler.NewAppHandler, handler.NewChatHistoryHandler)

var llmSet = wire.NewSet(
	ProvideChatModel,
)

func initServer(cfg *config.Config, userHandler *handler.UserHandler, appHandler *handler.AppHandler, chatHistoryHandler *handler.ChatHistoryHandler, userService service.IUserService) *server.Hertz {

	h := server.Default(server.WithHostPorts(fmt.Sprintf(":%d", cfg.Server.Port)), server.WithBasePath(cfg.Server.ContextPath))
	router.RegisterRoutes(h, userHandler, appHandler, chatHistoryHandler, userService)
	return h
}
