// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"fmt"
	"github.com/chosenlau/noCodeAI/config"
	"github.com/chosenlau/noCodeAI/internal/router"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// Injectors from wire.go:

func InitializeApp() (*server.Hertz, error) {
	hertz := initServer()
	return hertz, nil
}

// wire.go:

func initServer() *server.Hertz {
	cfg := config.GlobalConfig

	h := server.Default(server.WithHostPorts(fmt.Sprintf(":%d", cfg.Server.Port)), server.WithBasePath(cfg.Server.ContextPath))
	router.RegisterRoutes(h)
	return h
}
